version: '3'
services:
  postgres-actracker-search-feeder:
    image: 'postgres:15.1'
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

networks: # networks indentation moved to top level
  default:
    name: postgres-network