/*
 * This file is generated by jOOQ.
 */
package ovh.equino.actracker.searchfeed.jooq.tables.records;


import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import ovh.equino.actracker.searchfeed.jooq.tables.Dashboard;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DashboardRecord extends UpdatableRecordImpl<DashboardRecord> implements Record4<String, Long, Boolean, JSONB> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.dashboard.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.dashboard.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.dashboard.version</code>.
     */
    public void setVersion(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.dashboard.version</code>.
     */
    public Long getVersion() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.dashboard.deleted</code>.
     */
    public void setDeleted(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.dashboard.deleted</code>.
     */
    public Boolean getDeleted() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.dashboard.entity</code>.
     */
    public void setEntity(JSONB value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.dashboard.entity</code>.
     */
    public JSONB getEntity() {
        return (JSONB) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, Long, Boolean, JSONB> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, Long, Boolean, JSONB> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Dashboard.DASHBOARD.ID;
    }

    @Override
    public Field<Long> field2() {
        return Dashboard.DASHBOARD.VERSION;
    }

    @Override
    public Field<Boolean> field3() {
        return Dashboard.DASHBOARD.DELETED;
    }

    @Override
    public Field<JSONB> field4() {
        return Dashboard.DASHBOARD.ENTITY;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getVersion();
    }

    @Override
    public Boolean component3() {
        return getDeleted();
    }

    @Override
    public JSONB component4() {
        return getEntity();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getVersion();
    }

    @Override
    public Boolean value3() {
        return getDeleted();
    }

    @Override
    public JSONB value4() {
        return getEntity();
    }

    @Override
    public DashboardRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public DashboardRecord value2(Long value) {
        setVersion(value);
        return this;
    }

    @Override
    public DashboardRecord value3(Boolean value) {
        setDeleted(value);
        return this;
    }

    @Override
    public DashboardRecord value4(JSONB value) {
        setEntity(value);
        return this;
    }

    @Override
    public DashboardRecord values(String value1, Long value2, Boolean value3, JSONB value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DashboardRecord
     */
    public DashboardRecord() {
        super(Dashboard.DASHBOARD);
    }

    /**
     * Create a detached, initialised DashboardRecord
     */
    public DashboardRecord(String id, Long version, Boolean deleted, JSONB entity) {
        super(Dashboard.DASHBOARD);

        setId(id);
        setVersion(version);
        setDeleted(deleted);
        setEntity(entity);
    }
}
