/*
 * This file is generated by jOOQ.
 */
package ovh.equino.actracker.searchfeed.jooq;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ovh.equino.actracker.searchfeed.jooq.tables.Activity;
import ovh.equino.actracker.searchfeed.jooq.tables.FlywaySchemaHistory;
import ovh.equino.actracker.searchfeed.jooq.tables.Tag;
import ovh.equino.actracker.searchfeed.jooq.tables.records.ActivityRecord;
import ovh.equino.actracker.searchfeed.jooq.tables.records.FlywaySchemaHistoryRecord;
import ovh.equino.actracker.searchfeed.jooq.tables.records.TagRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ActivityRecord> ACTIVITY_PKEY = Internal.createUniqueKey(Activity.ACTIVITY, DSL.name("activity_pkey"), new TableField[] { Activity.ACTIVITY.ID }, true);
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<TagRecord> TAG_PKEY = Internal.createUniqueKey(Tag.TAG, DSL.name("tag_pkey"), new TableField[] { Tag.TAG.ID }, true);
}
