/*
 * This file is generated by jOOQ.
 */
package ovh.equino.actracker.searchfeed.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ovh.equino.actracker.searchfeed.jooq.tables.Activity;
import ovh.equino.actracker.searchfeed.jooq.tables.Dashboard;
import ovh.equino.actracker.searchfeed.jooq.tables.FlywaySchemaHistory;
import ovh.equino.actracker.searchfeed.jooq.tables.Tag;
import ovh.equino.actracker.searchfeed.jooq.tables.TagSet;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.activity</code>.
     */
    public final Activity ACTIVITY = Activity.ACTIVITY;

    /**
     * The table <code>public.dashboard</code>.
     */
    public final Dashboard DASHBOARD = Dashboard.DASHBOARD;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.tag</code>.
     */
    public final Tag TAG = Tag.TAG;

    /**
     * The table <code>public.tag_set</code>.
     */
    public final TagSet TAG_SET = TagSet.TAG_SET;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Activity.ACTIVITY,
            Dashboard.DASHBOARD,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Tag.TAG,
            TagSet.TAG_SET
        );
    }
}
