/*
 * This file is generated by jOOQ.
 */
package ovh.equino.actracker.searchfeed.jooq;


import ovh.equino.actracker.searchfeed.jooq.tables.Activity;
import ovh.equino.actracker.searchfeed.jooq.tables.Dashboard;
import ovh.equino.actracker.searchfeed.jooq.tables.FlywaySchemaHistory;
import ovh.equino.actracker.searchfeed.jooq.tables.Tag;
import ovh.equino.actracker.searchfeed.jooq.tables.TagSet;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.activity</code>.
     */
    public static final Activity ACTIVITY = Activity.ACTIVITY;

    /**
     * The table <code>public.dashboard</code>.
     */
    public static final Dashboard DASHBOARD = Dashboard.DASHBOARD;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.tag</code>.
     */
    public static final Tag TAG = Tag.TAG;

    /**
     * The table <code>public.tag_set</code>.
     */
    public static final TagSet TAG_SET = TagSet.TAG_SET;
}
