spec:
  template:
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: actracker-search-feeder-config
            - secretRef:
                name: actracker-search-feeder-rabbitmq-secret
            - secretRef:
                name: actracker-search-feeder-elasticsearch-secret
            - secretRef:
                name: actracker-search-feeder-postgres-app-secret
            - secretRef:
                name: actracker-search-feeder-postgres-owner-secret
      imagePullSecrets:
        - name: equino-registry
