spring:
  rabbitmq:
    host: ${actracker-search-feeder.rabbitmq.host:localhost}
    port: ${actracker-search-feeder.rabbitmq.port:5672}
    virtual-host: ${actracker-search-feeder.rabbitmq.vhost:/}
    username: ${actracker-search-feeder.rabbitmq.username:guest}
    password: ${actracker-search-feeder.rabbitmq.password:guest}
server:
  port: 8081
  servlet:
    context-path: /actracker-search-feeder
