/*
 * This file is generated by jOOQ.
 */
package ovh.equino.actracker.searchfeed.jooq.tables;


import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ovh.equino.actracker.searchfeed.jooq.Keys;
import ovh.equino.actracker.searchfeed.jooq.Public;
import ovh.equino.actracker.searchfeed.jooq.tables.records.TagSetRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagSet extends TableImpl<TagSetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.tag_set</code>
     */
    public static final TagSet TAG_SET = new TagSet();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TagSetRecord> getRecordType() {
        return TagSetRecord.class;
    }

    /**
     * The column <code>public.tag_set.id</code>.
     */
    public final TableField<TagSetRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.tag_set.version</code>.
     */
    public final TableField<TagSetRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.tag_set.deleted</code>.
     */
    public final TableField<TagSetRecord, Boolean> DELETED = createField(DSL.name("deleted"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.tag_set.entity</code>.
     */
    public final TableField<TagSetRecord, JSONB> ENTITY = createField(DSL.name("entity"), SQLDataType.JSONB.nullable(false), this, "");

    private TagSet(Name alias, Table<TagSetRecord> aliased) {
        this(alias, aliased, null);
    }

    private TagSet(Name alias, Table<TagSetRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.tag_set</code> table reference
     */
    public TagSet(String alias) {
        this(DSL.name(alias), TAG_SET);
    }

    /**
     * Create an aliased <code>public.tag_set</code> table reference
     */
    public TagSet(Name alias) {
        this(alias, TAG_SET);
    }

    /**
     * Create a <code>public.tag_set</code> table reference
     */
    public TagSet() {
        this(DSL.name("tag_set"), null);
    }

    public <O extends Record> TagSet(Table<O> child, ForeignKey<O, TagSetRecord> key) {
        super(child, key, TAG_SET);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TagSetRecord> getPrimaryKey() {
        return Keys.TAG_SET_PKEY;
    }

    @Override
    public TagSet as(String alias) {
        return new TagSet(DSL.name(alias), this);
    }

    @Override
    public TagSet as(Name alias) {
        return new TagSet(alias, this);
    }

    @Override
    public TagSet as(Table<?> alias) {
        return new TagSet(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TagSet rename(String name) {
        return new TagSet(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TagSet rename(Name name) {
        return new TagSet(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TagSet rename(Table<?> name) {
        return new TagSet(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, Long, Boolean, JSONB> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super String, ? super Long, ? super Boolean, ? super JSONB, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super String, ? super Long, ? super Boolean, ? super JSONB, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
